function [fitresult, gof] = createFit(t_shifted_filtered, I_t_shifted_filtered)
%CREATEFIT Fit a Gaussian amplitude to data.
%   [FITRESULT, GOF] = CREATEFIT(T_SHIFTED_FILTERED, I_T_SHIFTED_FILTERED)
%   fits the model A*exp(-2*(abs((x-B)/C).^2))+D to the provided data using
%   nonlinear least squares.
%
%   This function was auto-generated by MATLAB on 18-Jan-2024 14:05:22.
%
%   Inputs:
%       t_shifted_filtered - Time data (s).
%       I_t_shifted_filtered - Intensity data.
%
%   Outputs:
%       fitresult - Fit object of the Gaussian amplitude.
%       gof       - Goodness-of-fit statistics.

    [xData, yData] = prepareCurveData(t_shifted_filtered, I_t_shifted_filtered);

    ft = fittype('A*exp(-2*(abs((x-B)/C).^(2)))+D', 'independent', 'x', 'dependent', 'y');
    opts = fitoptions('Method', 'NonlinearLeastSquares');
    opts.DiffMinChange = 1e-16;
    opts.Display = 'Off';
    opts.Lower = [0 -1e-15 10e-15 -0.1];
    opts.StartPoint = [1.2 0 20e-15 0];
    opts.TolFun = 1e-10;
    opts.TolX = 1e-10;
    opts.Upper = [2 1e-15 50e-15 0.1];

    [fitresult, gof] = fit(xData, yData, ft, opts);

    figure('Name', 'Gaussian Amp');
    plot(fitresult, xData, yData);
    xlabel('t\_shifted\_filtered', 'Interpreter', 'none');
    ylabel('I\_t\_shifted\_filtered', 'Interpreter', 'none');
    grid off;
end
