%% HHG_Gouy_PM_v4_rework
% One-click script that runs the refactored Gouy phase and HHG analysis.
%
% Usage:
%   1. Update |parameterFilename| to point to your parameter text file.
%   2. Choose whether figures should be generated by adjusting |figureSwitch|.
%   3. Run the script from MATLAB or Octave.
%
% The workflow mirrors the legacy HHG_Gouy_PM_v4 function but is now
% modular: the heavy lifting is delegated to helper routines inside the
% |theory/hhg| folder.

parameterFilename = fullfile(pwd,'HHG_Gouy_PM_v4_Parameters.txt');
figureSwitch = 1;  % set to 0 to skip plotting

addpath(fullfile(pwd, '..', 'theory'));
addpath(fullfile(pwd, '..', 'theory','hhg'));
initializeHHGGlobals();
if ~isfile(parameterFilename)
    error('HHG_Gouy_PM_v4:ParameterFileMissing', ...
          'Parameter file %s not found.', parameterFilename);
end

params = loadHHGPMParameters(parameterFilename);

propagation = runHHGDrivingPulsePropagation(params, figureSwitch);

dipole = computeHHGDipolePhase(params, propagation, figureSwitch);

[hhgWavefront, result_scalar] = traceHHGWavefront(params, propagation, dipole, figureSwitch);

fprintf('HHG build-up efficiency (|E_{long}/E_{perfect}| at z_{end}): %g\n', result_scalar);
